import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, Loader2, Mail, MapPin, MessageCircle, Phone, RefreshCw, Send, ShieldCheck, XCircle } from "lucide-react";
import { useAuth } from "@/hooks/use-auth";
import { useI18n } from "@/hooks/use-i18n";
import { createAccessRequest, getMyAccessRequests, type AccessFeature, type AccessRequest } from "@/lib/access-requests-api";

const FEATURES: Array<[AccessFeature,string,string]> = [
  ["priority_zones","accessRequest.feature.priorityZones","accessRequest.feature.priorityZonesDesc"],
  ["zone_alerts","accessRequest.feature.zoneAlerts","accessRequest.feature.zoneAlertsDesc"],
  ["data_export","accessRequest.feature.dataExport","accessRequest.feature.dataExportDesc"],
  ["custom_ai_zone","accessRequest.feature.customAi","accessRequest.feature.customAiDesc"],
  ["sms_alerts","accessRequest.feature.sms","accessRequest.feature.smsDesc"],
  ["whatsapp_alerts","accessRequest.feature.whatsapp","accessRequest.feature.whatsappDesc"],
];

const phoneRegex = /^\+261\s?\d{2}\s?\d{2}\s?\d{3}\s?\d{2}$/;
function normalizeMgPhone(value:string){const digits=value.replace(/\D/g,"");if(digits.startsWith("261")&&digits.length===12)return "+"+digits;if(digits.startsWith("0")&&digits.length===10)return "+261"+digits.slice(1);return "";}
function formatMgPhone(value:string){const n=normalizeMgPhone(value);if(!n)return value.replace(/[^\d+\s]/g,"");const d=n.slice(4);return `+261 ${d.slice(0,2)} ${d.slice(2,4)} ${d.slice(4,7)} ${d.slice(7,9)}`;}
function PhoneField({value,onChange,required,label,placeholder}:{value:string;onChange:(v:string)=>void;required?:boolean;label:string;placeholder:string}){return <label className="block"><span className="mb-1.5 flex items-center gap-2 text-xs font-semibold"><Phone className="h-3.5 w-3.5 text-primary"/>{label}{required&&<span className="text-destructive">*</span>}</span><div className="flex items-center rounded-xl border bg-background px-3 shadow-sm focus-within:ring-2 focus-within:ring-primary/30"><span className="mr-2 text-xs font-semibold text-muted-foreground">+261</span><input value={value.replace(/^\+261\s*/,"")} onChange={e=>onChange(formatMgPhone("+261"+e.target.value.replace(/\D/g,"")))} placeholder={placeholder} inputMode="tel" className="h-11 min-w-0 flex-1 bg-transparent text-sm outline-none"/></div></label>}

function StatusCard({request,t}:{request:AccessRequest;t:(key:string)=>string}){
 const Icon=request.status==="approved"?CheckCircle2:request.status==="rejected"?XCircle:Clock3;
 const title=request.status==="approved"?t("accessRequest.status.approved"):request.status==="rejected"?t("accessRequest.status.rejected"):request.status==="contact_required"?t("accessRequest.status.contactRequired"):request.status==="under_review"?t("accessRequest.status.underReview"):t("accessRequest.status.pending");
 return <section className="rounded-2xl border border-border/70 bg-card/60 p-5 shadow-sm"><div className="flex gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5"/></div><div><h2 className="font-heading text-base font-semibold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{t("accessRequest.requestLabel",{id:request.id,organization:request.organization||"—"})}</p><p className="mt-2 text-sm text-muted-foreground">{request.status==="approved"?"Votre accès est maintenant actif. Vous pouvez continuer sans vous déconnecter.":"Créée le "+new Date(request.created_at).toLocaleString()}</p></div></div></section>
}

export default function AccessRequestPage(){
 const {user,hasExtendedAccess,refreshUser}=useAuth();
 const {t}=useI18n();
 const [requests,setRequests]=useState<AccessRequest[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState<string|null>(null); const [success,setSuccess]=useState<string|null>(null);
 const [organization,setOrganization]=useState(user?.organization||""); const [position,setPosition]=useState(""); const [phone,setPhone]=useState(user?.phone_number||""); const [whatsapp,setWhatsapp]=useState(user?.whatsapp_number||""); const [area,setArea]=useState("Madagascar"); const [project,setProject]=useState(""); const [duration,setDuration]=useState(""); const [reason,setReason]=useState(""); const [purpose,setPurpose]=useState(""); const [extra,setExtra]=useState(""); const [selected,setSelected]=useState<AccessFeature[]>(["priority_zones","zone_alerts"]);
 const load=useCallback(async(silent=false)=>{silent?setRefreshing(true):setLoading(true);try{const r=(await getMyAccessRequests()).requests;setRequests(r);setError(null)}catch(e){setError(e instanceof Error?e.message:t("accessRequest.error.load"))}finally{silent?setRefreshing(false):setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!hasExtendedAccess)return;const latest=requests[0];if(latest?.status==="approved"){void refreshUser()}},[hasExtendedAccess,requests,refreshUser]);
 const latest=requests[0]; const active=Boolean(latest&&["pending","under_review","contact_required"].includes(latest.status)); const approved=hasExtendedAccess||latest?.status==="approved";
 const submit=async()=>{const normalizedPhone=normalizeMgPhone(phone);const normalizedWhatsapp=whatsapp.trim()?normalizeMgPhone(whatsapp):"";if(approved||active||!phoneRegex.test(formatMgPhone(normalizedPhone))|| (whatsapp.trim()&&!phoneRegex.test(formatMgPhone(normalizedWhatsapp))) || reason.trim().length<20||purpose.trim().length<20||!selected.length)return;setBusy(true);setError(null);try{await createAccessRequest({reason:reason.trim(),purpose:purpose.trim(),organization:organization.trim()||undefined,position:position.trim()||undefined,contact_phone:formatMgPhone(normalizedPhone),contact_whatsapp:normalizedWhatsapp?formatMgPhone(normalizedWhatsapp):undefined,geographic_area:area.trim()||undefined,project_name:project.trim()||undefined,intended_duration:duration.trim()||undefined,requested_features:selected,additional_information:extra.trim()||undefined});setSuccess(t("accessRequest.success.submit"));setReason("");setPurpose("");setProject("");setDuration("");setExtra("");await load(true)}catch(e){setError(e instanceof Error?e.message:t("accessRequest.error.submit"))}finally{setBusy(false)}};
 if(loading)return <div className="flex min-h-[60vh] items-center justify-center text-sm text-muted-foreground"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>{t("accessRequest.loading")}</div>;
 return <div className="min-h-full bg-background px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1120px] space-y-6">
  <header className="border-b border-border/60 pb-5"><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-primary/5 px-3 py-1 text-[10px] font-bold uppercase tracking-wide text-primary"><ShieldCheck className="h-3 w-3"/>{t("accessRequest.badge")}</div><h1 className="font-heading text-2xl font-semibold">{approved?t("accessRequest.page.activeTitle"):t("accessRequest.page.requestTitle")}</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{approved?t("accessRequest.page.activeSubtitle"):t("accessRequest.page.requestSubtitle")}</p></header>
  {success&&<div className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-primary">{success}</div>}{error&&<div className="rounded-xl border border-destructive/20 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
  {latest&&<StatusCard request={latest} t={t}/>}
  {approved?<section className="rounded-2xl border border-primary/20 bg-primary/5 p-6 shadow-sm"><div className="flex items-start gap-4"><CheckCircle2 className="mt-0.5 h-7 w-7 shrink-0 text-primary"/><div><h2 className="font-heading text-lg font-semibold">{t("accessRequest.activeAccess.title")}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{t("accessRequest.activeAccess.description")}</p><p className="mt-3 text-xs font-medium text-primary">{t("accessRequest.activeAccess.hint")}</p></div></div></section>
  :!active&&<section className="overflow-hidden rounded-2xl border border-border/70 bg-card/60 shadow-sm"><div className="border-b bg-muted/25 px-5 py-4"><h2 className="font-heading text-base font-semibold">{t("accessRequest.requestSectionTitle")}</h2><p className="mt-1 text-xs text-muted-foreground">{t("accessRequest.requiredHint")}</p></div><div className="p-5 space-y-6">
   <div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-1.5 flex items-center gap-2 text-xs font-semibold"><Mail className="h-3.5 w-3.5 text-primary"/>{t("accessRequest.email")}</label><input value={user?.email||""} readOnly className="h-11 w-full rounded-xl border bg-muted/40 px-3 text-sm text-muted-foreground outline-none"/><p className="mt-1 text-[11px] text-muted-foreground">{t("accessRequest.emailHelp")}</p></div><div><label className="mb-1.5 flex items-center gap-2 text-xs font-semibold"><Phone className="h-3.5 w-3.5 text-primary"/>{t("accessRequest.phone")} <span className="text-destructive">*</span></label><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="+261 34 00 000 00" inputMode="tel" className="h-11 w-full rounded-xl border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/><p className="mt-1 text-[11px] text-muted-foreground">{t("accessRequest.phoneHelp")}</p></div></div>
   <div className="grid gap-4 sm:grid-cols-2"><div><label className="mb-1.5 flex items-center gap-2 text-xs font-semibold"><MessageCircle className="h-3.5 w-3.5 text-primary"/>{t("accessRequest.whatsapp")} <span className="text-[10px] font-normal text-muted-foreground">({t("accessRequest.optional")})</span></label><input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} placeholder="+261 34 00 000 00" inputMode="tel" className="h-11 w-full rounded-xl border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/></div><div><label className="mb-1.5 flex items-center gap-2 text-xs font-semibold"><MapPin className="h-3.5 w-3.5 text-primary"/>{t("accessRequest.area")}</label><select value={area} onChange={e=>setArea(e.target.value)} className="h-11 w-full rounded-xl border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"><option value="Madagascar">{t("accessRequest.area.madagascar")}</option><option value="Analamanga">{t("accessRequest.area.analamanga")}</option><option value="Boeny">{t("accessRequest.area.boeny")}</option><option value="Menabe">{t("accessRequest.area.menabe")}</option><option value="Atsinanana">{t("accessRequest.area.atsinanana")}</option><option value="Autre / plusieurs régions">{t("accessRequest.area.other")}</option></select></div></div>
   <div className="grid gap-4 sm:grid-cols-2"><input value={organization} onChange={e=>setOrganization(e.target.value)} placeholder={t("accessRequest.organization")} className="h-11 rounded-xl border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/><input value={position} onChange={e=>setPosition(e.target.value)} placeholder={t("accessRequest.position")} className="h-11 rounded-xl border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/><input value={project} onChange={e=>setProject(e.target.value)} placeholder={t("accessRequest.project")} className="h-11 rounded-xl border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/><select value={duration} onChange={e=>setDuration(e.target.value)} className="h-11 rounded-xl border bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"><option value="">{t("accessRequest.duration.placeholder")}</option><option value="lt3">{t("accessRequest.duration.lt3")}</option><option value="3to6">{t("accessRequest.duration.3to6")}</option><option value="6to12">{t("accessRequest.duration.6to12")}</option><option value="gt12">{t("accessRequest.duration.gt12")}</option><option value="tbd">{t("accessRequest.duration.tbd")}</option></select></div>
   <div><label className="mb-1.5 block text-xs font-semibold">{t("accessRequest.reason")} <span className="text-destructive">*</span></label><textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={20} rows={4} placeholder={t("accessRequest.reasonPlaceholder")} className="w-full rounded-xl border bg-background px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/><p className="mt-1 text-[11px] text-muted-foreground">{reason.trim().length}/20 {t("accessRequest.characters")}</p></div>
   <div><label className="mb-1.5 block text-xs font-semibold">{t("accessRequest.purpose")} <span className="text-destructive">*</span></label><textarea value={purpose} onChange={e=>setPurpose(e.target.value)} minLength={20} rows={4} placeholder={t("accessRequest.purposePlaceholder")} className="w-full rounded-xl border bg-background px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/><p className="mt-1 text-[11px] text-muted-foreground">{purpose.trim().length}/20 {t("accessRequest.characters")}</p></div>
   <div><label className="mb-2 block text-xs font-semibold">Fonctionnalités souhaitées</label><div className="grid gap-3 sm:grid-cols-2">{FEATURES.map(([value,label,desc])=><label key={value} className="flex cursor-pointer gap-3 rounded-xl border p-4 transition hover:border-primary/40 hover:bg-primary/5"><input type="checkbox" checked={selected.includes(value)} onChange={()=>setSelected(x=>x.includes(value)?x.filter(v=>v!==value):[...x,value])} className="mt-0.5 h-4 w-4"/><span><span className="block text-sm font-semibold">{label}</span><span className="mt-0.5 block text-xs text-muted-foreground">{desc}</span></span></label>)}</div></div>
   <div><label className="mb-1.5 block text-xs font-semibold">{t("accessRequest.additional")} <span className="text-[10px] font-normal text-muted-foreground">({t("accessRequest.optional")})</span></label><textarea value={extra} onChange={e=>setExtra(e.target.value)} rows={3} placeholder={t("accessRequest.additionalPlaceholder")} className="w-full rounded-xl border bg-background px-3 py-3 text-sm outline-none focus:ring-2 focus:ring-primary/30"/></div>
   <div className="flex flex-col gap-3 border-t pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs text-muted-foreground">{t("accessRequest.noPayment")}</p><button disabled={busy||!phoneRegex.test(formatMgPhone(normalizeMgPhone(phone)))||Boolean(whatsapp.trim()&&!phoneRegex.test(formatMgPhone(normalizeMgPhone(whatsapp))))||reason.trim().length<20||purpose.trim().length<20||!selected.length} onClick={()=>void submit()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground shadow-sm disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}{busy?t("accessRequest.submitting"):t("accessRequest.submit")}</button></div>
  </div></section>}
  {active&&<div className="rounded-xl border border-border/70 bg-card/60 p-5 text-sm"><strong>{t("accessRequest.active.title")}</strong><p className="mt-1 text-xs text-muted-foreground">{t("accessRequest.active.description")}</p><button onClick={()=>void load(true)} className="mt-3 inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold">{refreshing?<Loader2 className="h-3 w-3 animate-spin"/>:<RefreshCw className="h-3 w-3"/>}{t("accessRequest.refresh")}</button></div>}
  {requests.length>1&&<section className="space-y-3"><h2 className="font-heading text-sm font-semibold">{t("accessRequest.history")}</h2>{requests.slice(1,10).map(r=><StatusCard key={r.id} request={r} t={t}/>)}</section>}
 </div></div>;
}
