import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, Clock3, Loader2, RefreshCw, Send, ShieldCheck, XCircle } from "lucide-react";
import { useAuth } from "@/hooks/use-auth";
import { createAccessRequest, getMyAccessRequests, type AccessFeature, type AccessRequest } from "@/lib/access-requests-api";

const FEATURES: Array<[AccessFeature,string]> = [["priority_zones","Zones prioritaires"],["zone_alerts","Alertes sur zones"],["data_export","Export des données"],["custom_ai_zone","Zone IA personnalisée"],["sms_alerts","Alertes SMS"],["whatsapp_alerts","Alertes WhatsApp"]];
function StatusCard({request}:{request:AccessRequest}){const Icon=request.status==="approved"?CheckCircle2:request.status==="rejected"?XCircle:Clock3;const title=request.status==="approved"?"Accès étendu accordé":request.status==="rejected"?"Demande refusée":request.status==="contact_required"?"Échange nécessaire":request.status==="under_review"?"En cours d’examen":"Demande envoyée";return <section className="rounded-xl border border-border/70 bg-card/60 p-4 shadow-sm"><div className="flex gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5"/></div><div><h2 className="font-heading text-sm font-semibold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">Demande #{request.id} · {request.organization||"Organisation non renseignée"} · {request.status}</p><p className="mt-2 text-xs text-muted-foreground">{request.status==="approved"?"Reconnectez-vous pour obtenir une nouvelle session avec votre accès étendu.":"Créée le "+new Date(request.created_at).toLocaleString()}</p></div></div></section>}
export default function SubscriptionsPage(){
 const {user,isPremium}=useAuth();const [requests,setRequests]=useState<AccessRequest[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [refreshing,setRefreshing]=useState(false);const [error,setError]=useState<string|null>(null);const [success,setSuccess]=useState<string|null>(null);
 const [organization,setOrganization]=useState(user?.organization||"");const [position,setPosition]=useState("");const [phone,setPhone]=useState(user?.phone_number||"");const [area,setArea]=useState("Madagascar");const [project,setProject]=useState("");const [duration,setDuration]=useState("");const [reason,setReason]=useState("");const [purpose,setPurpose]=useState("");const [extra,setExtra]=useState("");const [selected,setSelected]=useState<AccessFeature[]>(["priority_zones","zone_alerts"]);
 const load=useCallback(async(silent=false)=>{silent?setRefreshing(true):setLoading(true);try{setRequests((await getMyAccessRequests()).requests);setError(null)}catch(e){setError(e instanceof Error?e.message:"Impossible de charger vos demandes.")}finally{silent?setRefreshing(false):setLoading(false)}},[]);
 useEffect(()=>{void load()},[load]);const active=Boolean(requests[0]&&["pending","under_review","contact_required"].includes(requests[0].status));
 const submit=async()=>{if(isPremium||active||reason.trim().length<20||purpose.trim().length<20||!selected.length)return;setBusy(true);setError(null);try{await createAccessRequest({reason:reason.trim(),purpose:purpose.trim(),organization:organization.trim()||undefined,position:position.trim()||undefined,contact_phone:phone.trim()||undefined,geographic_area:area.trim()||undefined,project_name:project.trim()||undefined,intended_duration:duration.trim()||undefined,requested_features:selected,additional_information:extra.trim()||undefined});setSuccess("Votre demande d’accès étendu a été envoyée.");setReason("");setPurpose("");setProject("");setDuration("");setExtra("");await load(true)}catch(e){setError(e instanceof Error?e.message:"Impossible d’envoyer la demande.")}finally{setBusy(false)}};
 if(loading)return <div className="flex min-h-[60vh] items-center justify-center text-sm text-muted-foreground"><Loader2 className="mr-2 h-4 w-4 animate-spin"/>Chargement…</div>;
 return <div className="min-h-full bg-background px-4 py-6 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1180px] space-y-6"><header className="border-b border-border/60 pb-5"><div className="mb-2 inline-flex items-center gap-2 rounded-full bg-primary/5 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-primary"><ShieldCheck className="h-3 w-3"/>Accès étendu</div><h1 className="font-heading text-2xl font-semibold">{isPremium?"Votre accès étendu":"Demander un accès étendu"}</h1><p className="mt-1 max-w-3xl text-sm text-muted-foreground">{isPremium?"Votre compte dispose déjà des fonctionnalités étendues.":"Présentez votre besoin opérationnel ou institutionnel afin qu’un administrateur puisse examiner votre demande."}</p></header>
 {success&&<div className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-primary">{success}</div>}{error&&<div className="rounded-xl border border-destructive/20 bg-destructive/5 p-3 text-sm text-destructive">{error}</div>}
 {requests[0]&&<StatusCard request={requests[0]}/>} 
 {!isPremium&&!active&&<section className="rounded-2xl border border-border/70 bg-card/60 p-5 shadow-sm"><div className="grid gap-3 sm:grid-cols-2"><input value={organization} onChange={e=>setOrganization(e.target.value)} placeholder="Organisation" className="h-10 rounded-lg border bg-background px-3 text-sm"/><input value={position} onChange={e=>setPosition(e.target.value)} placeholder="Fonction" className="h-10 rounded-lg border bg-background px-3 text-sm"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Téléphone" className="h-10 rounded-lg border bg-background px-3 text-sm"/><input value={area} onChange={e=>setArea(e.target.value)} placeholder="Zone géographique" className="h-10 rounded-lg border bg-background px-3 text-sm"/><input value={project} onChange={e=>setProject(e.target.value)} placeholder="Nom du projet" className="h-10 rounded-lg border bg-background px-3 text-sm"/><input value={duration} onChange={e=>setDuration(e.target.value)} placeholder="Durée souhaitée" className="h-10 rounded-lg border bg-background px-3 text-sm"/></div><div className="mt-4 space-y-3"><textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={20} rows={4} placeholder="Pourquoi demandez-vous un accès étendu ? (20 caractères minimum)" className="w-full rounded-lg border bg-background px-3 py-2.5 text-sm"/><textarea value={purpose} onChange={e=>setPurpose(e.target.value)} minLength={20} rows={4} placeholder="Quel sera l’usage de JeryMotro ? (20 caractères minimum)" className="w-full rounded-lg border bg-background px-3 py-2.5 text-sm"/><textarea value={extra} onChange={e=>setExtra(e.target.value)} rows={3} placeholder="Informations complémentaires (optionnel)" className="w-full rounded-lg border bg-background px-3 py-2.5 text-sm"/></div><h2 className="mt-5 text-sm font-semibold">Fonctionnalités souhaitées</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{FEATURES.map(([value,label])=><label key={value} className="flex items-center gap-2 rounded-lg border p-3 text-xs"><input type="checkbox" checked={selected.includes(value)} onChange={()=>setSelected(x=>x.includes(value)?x.filter(v=>v!==value):[...x,value])}/>{label}</label>)}</div><div className="mt-6 flex items-center justify-between gap-3 border-t pt-5"><span className="text-[11px] text-muted-foreground">Aucun paiement n’est demandé.</span><button disabled={busy||reason.trim().length<20||purpose.trim().length<20} onClick={()=>void submit()} className="inline-flex min-h-10 items-center gap-2 rounded-lg bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-50">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Send className="h-4 w-4"/>}{busy?"Envoi…":"Envoyer la demande"}</button></div></section>}
 {active&&<div className="rounded-xl border border-border/70 bg-card/60 p-5 text-sm"><strong>Une demande est déjà en cours.</strong><p className="mt-1 text-xs text-muted-foreground">Le formulaire reste désactivé pendant son traitement.</p><button onClick={()=>void load(true)} className="mt-3 inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold">{refreshing?<Loader2 className="h-3 w-3 animate-spin"/>:<RefreshCw className="h-3 w-3"/>}Actualiser</button></div>}
 {requests.length>1&&<section className="space-y-3"><h2 className="font-heading text-sm font-semibold">Historique des demandes</h2>{requests.slice(1,10).map(r=><StatusCard key={r.id} request={r}/>)}</section>}
 </div></div>
}