export type AccessRequestStatus = "pending" | "under_review" | "contact_required" | "approved" | "rejected" | "cancelled";
export type AccessFeature = "whatsapp_alerts" | "sms_alerts" | "priority_zones" | "zone_alerts" | "custom_ai_zone" | "data_export";
export interface AccessRequest { id:number; organization?:string|null; position?:string|null; contact_phone?:string|null; geographic_area?:string|null; project_name?:string|null; intended_duration?:string|null; reason:string; purpose:string; requested_features:AccessFeature[]; additional_information?:string|null; status:AccessRequestStatus; reviewed_at?:string|null; created_at:string; updated_at?:string|null; }
export interface MyAccessRequestListResponse { requests:AccessRequest[]; count:number; }
export interface AdminAccessRequest extends AccessRequest { user_id:number; requester_email:string; requester_name?:string|null; requester_role:string; admin_note?:string|null; reviewed_by?:number|null; }
export interface AdminAccessRequestListResponse { requests:AdminAccessRequest[]; count:number; total:number; limit:number; offset:number; }
function apiUrl(){const value=import.meta.env.VITE_API_URL;if(value&&(value.startsWith("http://")||value.startsWith("https://")||value.startsWith("/")))return value.replace(/\/+$/,"");const port=import.meta.env.VITE_API_BACKEND_PORT||"8081";return typeof window!=="undefined"?window.location.protocol+"//"+(window.location.hostname||"localhost")+":"+port:"http://localhost:"+port;}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const token=localStorage.getItem("jerymotro_token");if(!token)throw new Error("Session utilisateur absente.");const response=await fetch(apiUrl()+path,{...init,headers:{Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),...(init.headers||{}),Authorization:"Bearer "+token}});const ct=response.headers.get("content-type")||"";const payload=ct.includes("application/json")?await response.json():null;if(!response.ok){const detail=payload?.detail;const message=Array.isArray(detail)?detail.map((x:any)=>x?.msg||String(x)).join(" · "):detail;throw new Error(typeof message==="string"?message:"La requête a échoué ("+response.status+").");}return payload as T;}
export const getMyAccessRequests=()=>request<MyAccessRequestListResponse>("/access-requests/me");
export interface CreateAccessRequestPayload { reason:string; purpose:string; organization?:string; position?:string; contact_phone?:string; geographic_area?:string; project_name?:string; intended_duration?:string; requested_features:AccessFeature[]; additional_information?:string; }
export const createAccessRequest=(payload:CreateAccessRequestPayload)=>request<AccessRequest>("/access-requests",{method:"POST",body:JSON.stringify(payload)});
export const getAdminAccessRequests=(status?:AccessRequestStatus)=>{const query=new URLSearchParams({limit:"50",offset:"0"});if(status)query.set("status",status);return request<AdminAccessRequestListResponse>("/admin/access-requests?"+query.toString());};
export type AccessRequestDecisionPayload={admin_note?:string};
export const reviewAccessRequest=(id:number,payload:AccessRequestDecisionPayload={})=>request<AdminAccessRequest>("/admin/access-requests/"+id+"/review",{method:"POST",body:JSON.stringify(payload)});
export const contactAccessRequest=(id:number,payload:AccessRequestDecisionPayload={})=>request<AdminAccessRequest>("/admin/access-requests/"+id+"/contact",{method:"POST",body:JSON.stringify(payload)});
export const approveAccessRequest=(id:number,payload:AccessRequestDecisionPayload={})=>request<AdminAccessRequest>("/admin/access-requests/"+id+"/approve",{method:"POST",body:JSON.stringify(payload)});
export const rejectAccessRequest=(id:number,payload:AccessRequestDecisionPayload={})=>request<AdminAccessRequest>("/admin/access-requests/"+id+"/reject",{method:"POST",body:JSON.stringify(payload)});