export type AdminUserRole = "standard" | "premium" | "admin";
export interface AdminUser { id:number; email:string; full_name?:string|null; organization?:string|null; role:AdminUserRole; is_active:boolean; phone_number?:string|null; whatsapp_number?:string|null; phone_verified:boolean; }
export interface AdminUserListResponse { users:AdminUser[]; count:number; total:number; limit:number; offset:number; }
export interface AdminUserCreatePayload { email:string; password:string; full_name?:string; organization?:string; role?:AdminUserRole; phone_number?:string; whatsapp_number?:string; phone_verified?:boolean; is_active?:boolean; }
export interface AdminUserUpdatePayload extends Partial<Omit<AdminUserCreatePayload,"password">> { password?:string; }
function apiUrl(){const value=import.meta.env.VITE_API_URL;if(value&&(value.startsWith("http://")||value.startsWith("https://")||value.startsWith("/")))return value.replace(/\/+$/,"");const port=import.meta.env.VITE_API_BACKEND_PORT||"8081";return typeof window!=="undefined"?window.location.protocol+"//"+(window.location.hostname||"localhost")+":"+port:"http://localhost:"+port;}
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const token=localStorage.getItem("jerymotro_token");if(!token)throw new Error("Session administrateur absente.");const response=await fetch(apiUrl()+path,{...init,headers:{Accept:"application/json",...(init.body?{"Content-Type":"application/json"}:{}),...(init.headers||{}),Authorization:"Bearer "+token}});const ct=response.headers.get("content-type")||"";const payload=ct.includes("application/json")?await response.json():null;if(!response.ok){const detail=payload?.detail;const message=Array.isArray(detail)?detail.map((x:any)=>x?.msg||String(x)).join(" · "):detail;throw new Error(typeof message==="string"?message:`La requête a échoué (${response.status}).`);}return payload as T;}
export const getAdminUsers=(params:{q?:string;role?:AdminUserRole;is_active?:boolean;limit?:number;offset?:number}={})=>{const q=new URLSearchParams();if(params.q?.trim())q.set("q",params.q.trim());if(params.role)q.set("role",params.role);if(params.is_active!==undefined)q.set("is_active",String(params.is_active));q.set("limit",String(params.limit??50));q.set("offset",String(params.offset??0));return request<AdminUserListResponse>("/admin/users?"+q.toString());};
export const getAdminUser=(id:number)=>request<AdminUser>("/admin/users/"+id);
export const createAdminUser=(payload:AdminUserCreatePayload)=>request<AdminUser>("/admin/users",{method:"POST",body:JSON.stringify(payload)});
export const updateAdminUser=(id:number,payload:AdminUserUpdatePayload)=>request<AdminUser>("/admin/users/"+id,{method:"PATCH",body:JSON.stringify(payload)});
export const activateAdminUser=(id:number)=>request<AdminUser>("/admin/users/"+id+"/activate",{method:"POST"});
export const deactivateAdminUser=(id:number)=>request<AdminUser>("/admin/users/"+id+"/deactivate",{method:"POST"});
export const deleteAdminUser=(id:number)=>request<void>("/admin/users/"+id,{method:"DELETE"});
